cayley_nonunique_inverse:
  0: {0: 0, 1: 1, 2: 2}
  1: {0: 1, 1: 0, 2: 0}
  2: {0: 2, 1: 0, 2: 1}

cayley_noninvertible:
    0: {0: 0, 1: 1, 2: 2}
    1: {0: 1, 1: 2, 2: 0}
    2: {0: 2, 1: 1, 2: 1}

cayley_no_inverse:
    0: {0: 0, 1: 1, 2: 2}
    1: {0: 1, 1: 2, 2: 0}
    2: {0: 2, 1: 1, 2: 1}
