# Cayley tables for small groups written explicitly for testing

cayley_d3:
  e: {e: 'e', r: 'r', r^2: 'r^2', s: 's', rs: 'rs', r^2s: 'r^2s'}
  r: {e: 'r', r: 'r^2', r^2: 'e', s: 'rs', rs: 'r^2s', r^2s: 's'}
  r^2: {e: 'r^2', r: 'e', r^2: 'r', s: 'r^2s', rs: 's', r^2s: 'rs'}
  s: {e: 's', r: 'r^2s', r^2: 'rs', s: 'e', rs: 'r^2', r^2s: 'r'}
  rs: {e: 'rs', r: 's', r^2: 'r^2s', s: 'r', rs: 'e', r^2s: 'r^2'}
  r^2s: {e: 'r^2s', r: 'rs', r^2: 's', s: 'r^2', rs: 'r', r^2s: 'e'}

cayley_mod3:
  0: {0: 0, 1: 1, 2: 2}
  1: {0: 1, 1: 2, 2: 0}
  2: {0: 2, 1: 0, 2: 1}

cayley_mod4:
  0: {0: 0, 1: 1, 2: 2, 3: 3}
  1: {0: 1, 1: 2, 2: 3, 3: 0}
  2: {0: 2, 1: 3, 2: 0, 3: 1}
  3: {0: 3, 1: 0, 2: 1, 3: 2}

cayley_klein4:
  e: {e: e, a: a, b: b, c: c}
  a: {e: a, a: e, b: c, c: b}
  b: {e: b, a: c, b: e, c: a}
  c: {e: c, a: b, b: a, c: e}

cayley_s3:
  e: {e: e, p: p, q: q, r: r, s: s, t: t}
  p: {e: p, p: q, q: e, r: s, s: t, t: r}
  q: {e: q, p: e, q: p, r: t, s: r, t: s}
  r: {e: r, p: t, q: s, r: e, s: q, t: p}
  s: {e: s, p: r, q: t, r: p, s: e, t: q}
  t: {e: t, p: s, q: r, r: q, s: p, t: e}
