# Cayley tables for small groups written explicitly for testing

cayley_d4:
  e: {e: e, r: r, r^2: r^2, r^3: r^3, s: s, sr: sr, sr^2: sr^2, sr^3: sr^3}
  r: {e: r, r: r^2, r^2: r^3, r^3: e, s: sr^3, sr: s, sr^2: sr, sr^3: sr^2}
  r^2: {e: r^2, r: r^3, r^2: e, r^3: r, s: sr^2, sr: sr^3, sr^2: s, sr^3: sr}
  r^3: {e: r^3, r: e, r^2: r, r^3: r^2, s: sr, sr: sr^2, sr^2: sr^3, sr^3: s}
  s: {e: s, r: sr, r^2: sr^2, r^3: sr^3, s: e, sr: r, sr^2: r^2, sr^3: r^3}
  sr: {e: sr, r: sr^2, r^2: sr^3, r^3: s, s: r^3, sr: e, sr^2: r, sr^3: r^2}
  sr^2: {e: sr^2, r: sr^3, r^2: s, r^3: sr, s: r^2, sr: r^3, sr^2: e, sr^3: r}
  sr^3: {e: sr^3, r: s, r^2: sr, r^3: sr^2, s: r, sr: r^2, sr^2: r^3, sr^3: e}


cayley_mod3:
  0: {0: 0, 1: 1, 2: 2}
  1: {0: 1, 1: 2, 2: 0}
  2: {0: 2, 1: 0, 2: 1}

cayley_mod4:
  0: {0: 0, 1: 1, 2: 2, 3: 3}
  1: {0: 1, 1: 2, 2: 3, 3: 0}
  2: {0: 2, 1: 3, 2: 0, 3: 1}
  3: {0: 3, 1: 0, 2: 1, 3: 2}

cayley_klein4:
  e: {e: e, a: a, b: b, c: c}
  a: {e: a, a: e, b: c, c: b}
  b: {e: b, a: c, b: e, c: a}
  c: {e: c, a: b, b: a, c: e}

cayley_s3:
  e: {e: e, p: p, q: q, r: r, s: s, t: t}
  p: {e: p, p: q, q: e, r: s, s: t, t: r}
  q: {e: q, p: e, q: p, r: t, s: r, t: s}
  r: {e: r, p: t, q: s, r: e, s: q, t: p}
  s: {e: s, p: r, q: t, r: p, s: e, t: q}
  t: {e: t, p: s, q: r, r: q, s: p, t: e}
